### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by arlk** [RoboticExplorationLab/TrajectoryOptimization.jl#18]
Thanks for this neat library! I have been using it in my work and wanted to know if you had a preferred way to cite this work. I haven't used ALTRO specifically, but just the iLQR solver - so I wasn't sure if I should cite the IROS paper or not.

**Comment by bjack205** [comment]
Sorry for not seeing this earlier. We don't have a citation for the package yet. You can either cite the paper or just give a link to the repository, for now. 

Glad you've found it useful! If you haven't already, be sure to check out the code on the master branch. We got a massive speedup (sometimes about 100x) after some intense code re-structuring.

**Comment by arlk** [comment]
Thanks! 👍
