### ISSUE TITLE
Problems running the example code

### ISSUE THREAD

**Issue by VladimirIvan** [RoboticExplorationLab/TrajectoryOptimization.jl#20]
Hi,
I'm struggling to get the example code to run.
I'm getting the following error messages when running the example code from the readme file:
```
model = Model(dynamics!,n,m) # create model
ERROR: UndefVarError: Model not defined
```

I also tried to run the example scripts. In ```examples/pendulum.jl``` I get:
```
LoadError: MethodError: Cannot `convert` an object of type iLQRSolverOptions{Float64} to an object of type TrajectoryOptimization.UnconstrainedSolverOptions{Float64}
```

The cartpole and couple others fail with the same massage.
I'm using Julia 1.4.0 and I'm on the the latest master.
Any pointers?

**Comment by bjack205** [comment]
Ah, yes, the README is out of date, I apologize. That notation is for the old API!

Try looking in the `/examples` directory for some working examples. I'll get the README updated.

**Comment by bjack205** [comment]
README has been updated. The documentation is (mostly) up-to-date and should be helpful. This project is still under very active development so don't hesitate to reach out if you find an issue!
