### ISSUE TITLE
Examples folder do not contain the examples from the paper

### ISSUE THREAD

**Issue by sz73** [RoboticExplorationLab/TrajectoryOptimization.jl#29]
Hi,
unlike it says at the end of the [readme](https://github.com/RoboticExplorationLab/TrajectoryOptimization.jl#examples)

> # Examples
> Notebooks with more detailed examples can be found here, including all the examples from our IROS 2019 paper.

only the quickstart.jl file is provided.

Could you please make the files available?

Best 
Simon

**Comment by wangyubin11** [comment]
Excuse. need the example the paper recommended too. And looking forward to reply.

**Comment by bjack205** [comment]
IROS examples were included in the original release, v0.1, and located [here](https://github.com/RoboticExplorationLab/TrajectoryOptimization.jl/tree/v0.1.2/examples/IROS_2019)

Similar examples on v0.2 are located [here](https://github.com/RoboticExplorationLab/TrajectoryOptimization.jl/tree/v0.2.0/examples)

For the newest version, similar examples are located [here](https://github.com/RoboticExplorationLab/ALTRO.jl/tree/master/problems)
