### ISSUE TITLE
Working examples and "stable" dev branch

### ISSUE THREAD

**Issue by ferrolho** [RoboticExplorationLab/TrajectoryOptimization.jl#3]
Hello! I would like to run and test some of the things implemented here. I am aware of the `development` and `dev_notebooks` folders, but I'm having some minor issues trying to run them.

The most up-to-date branch is `restructure`, right? Are there any working examples, something along the lines of `development/paper/kuka_tests.jl`?

**Comment by bjack205** [comment]
The restructure branch is currently undergoing some pretty big changes, and hasn't been thoroughly tested yet. I just pushed `/demos/quadrotor_demo.jl` on the `restructure` branch with an example running through our old way (everything on the `master` branch) and our new way. The documentation has also been updated.

`/development/paper/kuka_tests.jl` is running for me on the `master` branch. We've verified it works on both Linux and Windows. If you let us know what your error message is we might be able to help you more. 

Sorry for the late reply, we've been out on Spring Break.

**Comment by ferrolho** [comment]
> Are there any working examples, something along the lines of `development/paper/kuka_tests.jl`?

Sorry, the way I framed my question was not very good indeed. I can run `kuka_tests.jl` without a problem. At the time I was looking for other working examples. I have managed to run some bits and pieces after that anyway.

Thank you for your reply! I'm looking forward to a more stable release and to read your paper. (Have you perhaps submitted an arxiv version?)

**Comment by bjack205** [comment]
The paper is available on our lab website: rexlab.stanford.edu (it's the most recent one, with ALTRO in the title). We should have the restructure branch fully-featured and tested within the next week or so. If you're looking for examples, we have a bunch buried in tests (although the comments aren't great in there). In the meantime, if you have a specific thing you'd like to get going and aren't sure how to get it to work, let us know.

**Comment by thowell** [comment]
The final version of the paper is available here: https://rexlab.stanford.edu/papers/altro-iros.pdf
Many examples, including notebooks and all results from the paper, can be found here: https://github.com/RoboticExplorationLab/TrajectoryOptimization.jl/tree/master/examples

Additionally, a stable release can be downloaded from the Julia package manager.
