### ISSUE TITLE
Git error checking out master due to filename "Underactuated Double Pendulum | Acrobot.ipynb"

### ISSUE THREAD

**Issue by avikde** [RoboticExplorationLab/TrajectoryOptimization.jl#5]
This is the error from git (git version 2.17.1.windows.2) on Windows 10.

`error: unable to create file examples/double pendulum/Underactuated Double Pendulum | Acrobot.ipynb: Invalid argument`

Changing the "|" to "-" is a fine solution.

**Comment by bjack205** [comment]
Renamed the file and it should work now. Thanks for catching it.
