### ISSUE TITLE
RA-L example on the distributed_team_lift branch

### ISSUE THREAD

**Issue by MAminSFV** [RoboticExplorationLab/TrajectoryOptimization.jl#53]
I have been trying to reproduce your simulations on the RA-L paper, Scalable Cooperative Transport of Cable-Suspended
Loads with UAVs using
Distributed Trajectory Optimization, which was published recently. I really liked the idea and wanted to use the methodology for my master thesis.

However, it seems that there is a Julia environment problem, and I could not run the code. It seems like there is a version problem with some of the packages. 
I could not resolve the manifest, and there are two environments; one is inside the RA-L, and there are references from outside of that environment.

I would really appreciate it if you could help me with the compatibility issues related to that branch and that specific example.

@thowell @bjack205 @zacmanchester 

Thank you for your amazing work!

**Comment by thowell** [comment]
Please check this issue: https://github.com/RoboticExplorationLab/TrajectoryOptimization.jl/pull/52. Jayesh recently (last week) fixed the version issues and was able to run our experiments.

**Comment by AbhinayNS** [comment]
I am also trying to reproduce the results, it would be helpful if you could create a readme file containing details like which files correspond to the different results presented in the paper
