### ISSUE TITLE
Example Bug

### ISSUE THREAD

**Issue by kevin-tracy** [RoboticExplorationLab/TrajectoryOptimization.jl#6]
On the readme, the example fails to run because it can't locate the rk3 function.

**Comment by rffc14** [comment]
> On the readme, the example fails to run because it can't locate the rk3 function.

Hello Kevin, did you added the package to Julia correctly? That was the source of many problems when I started trying this.

**Comment by thowell** [comment]
Hi Kevin,

I did a fresh install of Ubuntu, Julia, and the package and didn't have any issues running the example. Do you have a current version of Julia, 1.0 or newer?

**Comment by bjack205** [comment]
It looks like there's a bug in the current v0.1.0 release, which has been fixed on the master branch. I'll submit a request for a new version.
